title: Alice Ma
description: Personal portfolio and job search page
url: https://amecila1.github.io
baseurl: ""

email: alicetyma@gmail.com
github_username: amecila1
linkedin_username: "" # add your LinkedIn username, e.g. alice-ma
