title: Alice Ma's personal website
description: Personal portfolio website where Alice shares her projects and experiences.
url: https://amecila1.github.io
baseurl: ""

email: alicetyma@gmail.com
github_username: amecila1
linkedin_username: alicetyma
